#!/bin/sh

#this script removes a marked ip address from the iptables
if [ $# -eq 3 ]
then
	MARK=$1
	MAC=$2
	IP=$3
	echo $1 , $2 ,$3
	#DOWNLINK
	iptables -D FORWARD -t mangle -d ${IP} -j MARK --set-mark $MARK
else
	echo "Wrong number of Arguments!"
fi
