#!/bin/sh

#comment the variables to hardcode them
#UPLINK
PORT2=enp3s0f0

CLASSID=$1
var1=$2
var3=8
URATE=$((var1/var3))
PRIO=$1

# RATE LIMITING CLASS AS DEFINED BY USER GIVEN VALUES

#UPLINK
tc class add dev "$PORT2" parent 2:0 classid 2:"$CLASSID" htb rate "$URATE"kbps ceil "$URATE"kbps prio $PRIO
tc filter add dev "$PORT2" parent 2:0 prio "$PRIO" protocol ip handle "$CLASSID" fw flowid 2:"$CLASSID"
echo $1 , $URATE , $PRIO
