#!/bin/sh
#removes the filter for the specified mark
#DOWLINK
PORT1=enp3s0f1
CLASSID=$1
var2=$2
var3=8
DRATE=$((var2/var3))
PRIO=$1
echo $1 , $DRATE
#DOWNLINK
tc filter del dev $PORT1 prio $PRIO
tc class del dev $PORT1 classid 1:$CLASSID


