#!/bin/sh
#removes the filter for the specified mark
#DOWLINK
PORT1=enp3s0f1
#UPLINK
PORT2=enp3s0f0
CLASSID=$1
var1=$2
var2=$3
var3=8
URATE=$((var1/var3))
DRATE=$((var2/var3))
PRIO=$1
echo $1 , $2 , $3
#DOWNLINK
tc filter del dev $PORT1 prio $PRIO
tc class del dev $PORT1 classid 1:$CLASSID
#UPLINK
tc filter del dev $PORT2 prio $PRIO
tc class del dev $PORT2 classid 2:$CLASSID

