#!/bin/sh

#comment the variables to hardcode them
#DOWNLINK
PORT1=enp3s0f1
CLASSID=$1
var2=$2
var3=8
#URATE=$((var1/var3))
DRATE=$((var2/var3))
PRIO=$1

# RATE LIMITING CLASS AS DEFINED BY USER GIVEN VALUES
#DOWNLINK
echo $1 , $DRATE , $PRIO
tc class add dev "$PORT1" parent 1:0 classid 1:"$CLASSID" htb rate "$DRATE"kbps ceil "$DRATE"kbps prio $PRIO
tc filter add dev "$PORT1" parent 1:0 prio "$PRIO" protocol ip handle "$CLASSID" fw flowid 1:"$CLASSID"
echo $1 , $DRATE , $PRIO

